
save:
	cp factorio/saves/bp-decoder-1.1.19.zip .
	cp factorio/blueprint-storage.dat .

restore:
	cp blueprint-storage.dat factorio/blueprint-storage.dat
	cp factorio/saves/bp-decoder-1.1.19.zip bp-decoder-1.1.19.zip


