
save:
	cp factorio/saves/bp-decoder-1.0.0.zip .
	cp factorio/blueprint-storage.dat .

restore:
	cp blueprint-storage.dat factorio/blueprint-storage.dat
	cp factorio/saves/bp-decoder-1.0.0.zip bp-decoder-1.0.0.zip


